language: node_js
node_js:
- "stable"
after_success:
- npm run coveralls
services:
  - postgresql
before_script:
  - psql -c 'create database hellobooks_test;' -U postgres
  - psql -c "CREATE USER root WITH PASSWORD 'password';" -U postgres
script:
  - npm install
  - npm run test
env:
  - dialect=postgres
  - NODE_ENV=test
