export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const ADD_BOOK = 'ADD_BOOK';
export const GET_ALL_BOOKS = 'GET_BOOKS';
export const DELETE_BOOK = 'DELETE_BOOK';
export const EDIT_BOOK = 'GET_BOOK';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const BORROW_BOOK = 'BORROW_BOOK';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const GET_UNRETURNED_BOOKS = 'GET_BORROWED_BOOKS';
export const RETURN_BOOK = 'RETURN_BOOK';
export const GET_BORROWED_HISTORY = 'GET_BORROWED_HISTORY';

